# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 10:44
from __future__ import unicode_literals

import composer.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='/songs/', validators=[composer.validators.validate_file_extension])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composer.Project')),
            ],
        ),
    ]
