# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0002_project_nr_of_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='nr_of_songs',
            field=models.IntegerField(default=0),
        ),
    ]
