# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0003_auto_20170423_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='nr_of_songs',
            new_name='no_of_songs',
        ),
    ]
